<div class="margin-bottom-15">
	<h3><?php echo $this->escapeHtml($this->user->getUsername()) ?></h3>
	<hr/>
	<ul class="list-unstyled">
		<?php if($this->isAllowed('user')){ ?>
			<li><a href="<?php echo $this->url('user') ?>"><i class="glyphicon glyphicon-user"></i> Accountpanel</a></li>
		<?php } ?>
		<?php if($this->isAllowed('zfc-ticketsystem')){ ?>
		<li><a href="<?php echo $this->url('zfc-ticketsystem') ?>"><i class="fa fa-graduation-cap"></i> TicketSystem</a></li>
		<?php } ?>
		<?php if($this->isAllowed('admin_home')){ ?>
		<li><a href="<?php echo $this->url('admin_home') ?>"><i class="fa fa-graduation-cap"></i> Adminpanel</a></li>
		<?php } ?>
	</ul>
</div>