<?php
    $params = isset($this->params)?$this->params:array();
    $format = isset($this->ajax)?'#"onclick="paginatorAjax(\''.$this->ajax.'\',\'%s\')"':'%s';
?>

<?php if ($this->pageCount): ?>
    <div class="text-center">
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <?php
                $params['page'] = $this->previous;
                $url = sprintf( $format, $this->url($this->route, $params));
                ?>
                <li>
                    <a href="<?= $url; ?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <?php
                    $params['page'] = $page;
                    $url = sprintf( $format, $this->url($this->route, $params));
                    ?>
                    <li>
                        <a href="<?= $url; ?>">
                            <?= $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?= $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <?php
                $params['page'] = $this->next;
                $url = sprintf( $format, $this->url($this->route, $params));
                ?>
                <li>
                    <a href="<?= $url; ?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>