<div>
    <h3><?= $this->translate('Server Info') ?></h3>
    <hr/>
    <ul class="list-unstyled">
        <li><b><?= $this->translate('PlayerOnline') ?></b> <?= $this->playerHistory() ?></li>
        <?php if((bool)$this->serverInfo): ?>
            <?php foreach($this->serverInfo as $curInfo): ?>
                <?php /** @var \PServerCMS\Entity\ServerInfo $curInfo */ ?>
                <li>
                    <i class="<?= $this->escapeHtml($curInfo->getIcon()) ?>"></i>
                    <b><?= $this->escapeHtml($curInfo->getLabel()) ?></b>
                    <?= $this->escapeHtml($curInfo->getMemo()) ?>
                </li>
            <?php endforeach ?>
        <?php endif ?>
    </ul>
</div>