<div class="margin-top-30">
    <h3><?= $this->translate('Servertime') ?></h3>
    <hr/>
    <ul class="list-unstyled">
        <li><i class="fa fa-clock-o"></i> <?= $this->translate('Timer') ?>: <span id="idTimerClock"><?php echo date('H:i:s') ?></span></li>
        <?php $i=0; ?>
        <?php if ((bool)$this->timer ): ?>
            <?php foreach ($this->timer as $curTimer) : ?>
                <li><i class="<?= $this->escapeHtml($curTimer['icon']) ?>"></i>
                    <?= $curTimer['name'] ?>:
                    <?php if ($curTimer['time'] > 0) { ?>
                        <span class="timerCountdown" id="<?php echo 'idTimeCountdown_'.$i++; ?>" data-time="<?= $curTimer['time'] ?>"></span>
                    <?php } else { ?>
                        <?= $this->escapeHtml($curTimer['text']) ?>
                    <?php } ?>
                </li>
            <?php endforeach ?>
        <?php endif ?>
    </ul>
</div>