<?php if ($this->guildList) : ?>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>#</th>
                <th><?= $this->translate('Guild') ?></th>
                <th><?= $this->translate('Level') ?></th>
            </tr>
            </thead>
            <?php
            $i = 1;
            foreach ($this->guildList as $key => $guild) :
                /** @var $guild \GameBackend\Entity\Game\GuildInterface */
                ?>
                <tr>
                    <td><?= $i++; ?></td>
                    <td>
                        <a href="<?= $this->url('PServerRanking/guild', ['id' => $guild->getId() ]) ?>">
                            <?= $guild->getName() ?>
                        </a>
                    </td>
                    <td><?= $guild->getLevel() ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
<?php endif; ?>