<?php include '_salutation.phtml' ?>
Please click on the following link to change your password.<br />
<br />
<a href="<?php echo $this->url('small-user-auth', array('action' => 'pw-lost-confirm', 'code' => $this->code), array('force_canonical' => true)); ?>">
	<?php echo $this->url('small-user-auth', array('action' => 'pw-lost-confirm', 'code' => $this->code), array('force_canonical' => true)); ?>
</a>