<?php include '_salutation.phtml' ?>
Thank you for registration.<br />
Please confirm your account by clicking on the following link.<br />
<br />
<a href="<?php echo $this->url('small-user-auth', array('action' => 'register-confirm', 'code' => $this->code), array('force_canonical' => true)); ?>">
	<?php echo $this->url('small-user-auth', array('action' => 'register-confirm', 'code' => $this->code), array('force_canonical' => true)); ?>
</a><br/>
<br />
Hope you will enjoy the game and good luck!